<?php

namespace backend\modules\recipes\models;

use common\models\Debug;
use common\models\IngrToRecipes;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "recipes".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property int $status
 * @property string $slug
 * @property string $dt_add
 *
 * @property IngrToRecipes[] $ingrToRecipes
 */
class Recipes extends \common\models\Recipes
{
	public $ingrToRecipes;
	public function behaviors() {
		return [
			'slug' => [
				'class'         => 'common\behaviors\Slug',
				'in_attribute'  => 'name',
				'out_attribute' => 'slug',
				'translit'      => true
			],
		];
	}
	
//	public function setDescription( $value ) {
//		$this->description = json_encode( $value );
//	}
//	public function getDescription() {
//		return json_decode( $this->description );
//	}
	
//	public function beforeSave( $insert ) {
//
//		$this->setDescription($this->description);
//		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
//	}
	
	public function beforeSave( $insert ) {
		$post = $_POST['Recipes'];
		
		if($post['ingrToRecipes']) {
			IngrToRecipes::deleteAll(['recipes_id'=>$this->id]);
			foreach ($post['ingrToRecipes'] as $ingr) {
				$ingredient = new IngrToRecipes();
				$ingredient->recipes_id = $this->id;
				$ingredient->ingredients_id = $ingr;
//				$ingredient->status = 1;
				$ingredient->save();
			}
		}
		
		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
	}

	
}
