<?php

namespace backend\modules\ingredients\models;

use common\models\Property;
use common\models\PropertyConnIngredients;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "ingredients".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property int $status
 * @property string $dt_add
 */
class Ingredients extends \common\models\Ingredients
{
	
	
	public function beforeSave( $insert ) {
		$post = $_POST['Ingredients'];

		if($post['propertyConnIngredients']) {
			PropertyConnIngredients::deleteAll(['ingredients_id'=>$this->id]);
			foreach ($post['propertyConnIngredients'] as $prop) {
					$property = new PropertyConnIngredients();
					$property->ingredients_id = $this->id;
					$property->property_id = $prop;
					$property->status = 1;
					$property->save();
			}
		}
		
		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
	}
}
